# Generated by Django 5.2.6 on 2025-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ID номер чата в телеграм",
            ),
        ),
    ]
